### PR TITLE
Release 1.6.3

### PR DESCRIPTION
**Pull request by KengoTODA**
@spotbugs/everyone Please review this PR to support Gradle 4.10. Thanks a lot!

### CODE REVIEW

**Comment by henrik242** [comment]
@KengoTODA  You should probably update the gradle versions in .travis.yml as well

**Comment by henrik242** [comment]
oracle-java8-set-default_8u151-1~webupd8~0_all.deb is missing from http://ppa.launchpad.net/webupd8team/java/ubuntu/pool/main/o/oracle-java8-installer/ , but u181 is there.  Maybe we need an apk update / upgrade in before_script in .travis.yml as well?

**Comment by KengoTODA** [comment]
@henrik242 I've force pushed the changes that enable `apt-get update` before the build, let's wait the build result...

**Comment by KengoTODA** [comment]
> You should probably update the gradle versions in .travis.yml as well

After we switch to Gradle 4.10, change `env.matrix` as follows:

```
    - GRADLE_VERSION=default
    - GRADLE_VERSION=4.11-20180823092818+0000
    - GRADLE_VERSION=5.0-20180906235859+0000
```

**Comment by henrik242** [comment]
@KengoTODA Looks good! By the way, I'm not authorized to merge in this repo (only in the main repo), could you add me?

**Comment by KengoTODA** [comment]
Thanks @henrik242, I've invited you to this repo so please check it!

**Comment by chali** [comment]
Hi @KengoTODA 

Regarding:
> After we switch to Gradle 4.10, change env.matrix as follows:

You can skip 4.11 because that are older nightly builds which later became 5.0. 5.0 is going through pretty big changes so you will need to keep 5.0 version up to data to have guarantees that everything is still working. We will be working on migration for our plugins so we will be discovering possible issues in following weeks.

**Comment by KengoTODA** [comment]
@chali thank you, I've stopped using 4.11 in #50.

**Pull request merged**
