### PR TITLE
🚀 Ship the major release v6

### PR DESCRIPTION
**Pull request by KengoTODA**
This PR will publish the v6 as a stable release. 

We have [shipped the first release candidate version on Oct/18](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/6.0.0-rc.1), and if there is no critical feedback from users, merge this PR to release the `6.0.0`.

### CODE REVIEW

**Comment by hazendaz** [comment]
@KengoTODA Probably best to wait before final to pick up bug fixes from spotbugs.  Maybe another RC then if needed.  The spotbugs fixes should be only isolated the 4.8.0 bugs that rolled out.  I think there is at least one more thing to address first so that should be out sometime next week.

**Comment by hazendaz** [comment]
@KengoTODA 4.8.1 is out if you want to get this updated and released out.  Seems some conflicts to address and you may want to look at the outstanding PRs to see if just picking up non functional ones previously left until after can just come now.

**Comment by hazendaz** [comment]
well sort of our, forgot to release from nexus staging.  Doing that now.

**Comment by hazendaz** [comment]
Moved to draft, needs fixed up and lets wait another week here until we get 4.8.2 out.  Few more issues we are working through and best IMO to have a really good 6.0.0 release here that isn't getting changed frequently.

**Comment by KengoTODA** [comment]
@hazendaz seems that 4.8.2 has not been released, so I want to use an old but stable version to use as the default spotbugs version.
I think 4.8.0 is enough, please tell me if 4.7.3 is better to choose.

**Comment by hazendaz** [comment]
@KengoTODA If sticking to 4.8.x, use 4.8.1.  But do check the change log to make sure issues with it are acceptable.  I think there are a few mainly new things coming in that are almost done then think 4.8.2 will be out.  Not trying to rush others but 4.8.1 was far more stable.  Of course, if you wanted to go back to 4.7.3 that would be fine too.  But given you did another RC then maybe a week to work that out would be acceptable.

**Comment by KengoTODA** [comment]
OK, then I'll use `v4.8.1` to follow the usual release policy (always use the latest release as default version), and bump up it to `v4.8.2` when it becomes ready to use.

**Comment by KengoTODA** [comment]
@hazendaz This branch is ready to merge, please check and approve this PR when you have time. I know that this PR is huge to review, but we've spent months to get feedback for beta releases and RC releases so I believe it's OK to publish this as `6.0.0`.

**Comment by hazendaz** [comment]
@KengoTODA Good new!, I'll be releasing spotbugs 4.8.2 tonight so we will be able to move there too.  Will circle back here once that is done.

**Comment by KengoTODA** [comment]
@hazendaz I've updated the master branch to use SpotBugs 4.8.2. Congrats!

**Comment by hazendaz** [comment]
@KengoTODA Will look at this tomorrow night.  Thanks.

**Comment by hazendaz** [comment]
@KengoTODA Are the auto generated .idea files really necessary here?  I typically would bock those.

**Review by hazendaz — APPROVED** [review]

**Comment by KengoTODA** [comment]
> @KengoTODA Are the auto generated .idea files really necessary here? I typically would bock those.

Things that we should ignore are already listed in the `.gitignore`, so I believe it's OK to commit these files.

Thanks for your review!

**Pull request merged**
