### PR TITLE
docs: Update README.md - fix typo

### PR DESCRIPTION
**Pull request by 7Adrian**
Documentation doesn't display property.

Changes Readme

### CODE REVIEW

**Review by KengoTODA — APPROVED** [review]
LGTM, thank you!

**Comment by hazendaz** [comment]
@7Adrian can you redo your commit and prefix it with 'docs:' so it passes this new check we have

```
allowed-commit-types: feat,fix,docs,style,refactor,test,build,perf,ci,chore,revert,merge,wip
```

@KengoTODA Maybe not needed, will leave that to you.  I assume if merged in failed state it won't check this commit again anyways and its not harmful given its just an empty line add to readme but I don't want to assume :)

**Comment by 7Adrian** [comment]
@hazendaz is it ok now, or I should use `git commit --fixup`? 

Oh and one more thing you can consider. Since `gradle 8.3` command `$buildDir` is marked as deprecated. Based on gradle documentation `Deprecations` section for `Upgrading from 8.2 and earlier`:

[Gradle documentation upgrading from 8.2 and earlier](https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecations_3)

Gradle suggest replacement (example from README.md):

```groovy
outputLocation = file("$buildDir/reports/spotbugs.html")
```
to

```groovy
outputLocation = layout.buildDirectory.file("reports/spotbugs.html")
```

or (I tested that option for blank project and it seems work)

```groovy
outputLocation = layout.buildDirectory.file("reports/spotbugs.html").get().asFile
```

I'm fairly new to open source and not sure what to do with that (creating new issue, adding commit to this pull request, create new pull request, discuss on some forum), any tips are welcome.

**Review by hazendaz — APPROVED** [review]

**Comment by hazendaz** [comment]
@7Adrian I can at least quash this now to comply with the naming.  Typically what you would have wanted to do was just amend the commit you had so just one commit.  Then force pushed that back up.  The second commit you added while has the correct naming is empty but we squash anyways so I can work with that.  

Feel free to submit a new PR for any other updates you see this needs.

**Pull request merged**
