### PR TITLE
ci: introduce semantic-release

### PR DESCRIPTION
**Pull request by KengoTODA**
Currently we need at least two PRs to make a release, like #167 and #168. This makes release procedure complex, and our release slow.

This PR introduces [the semantic-release](http://semantic-release.org/) that automates release from `master` branch.
It requests all contributors to follow [the Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/), so CI will verify the Git commit messages in PR.

### CODE REVIEW

**Comment by KengoTODA** [comment]
@spotbugs/everyone CI builds have been passed. Please review this PR. Thanks in advance!

**Comment by ThrawnCA** [comment]
If we're following semantic versioning, then we're supposed to start by publishing an API.

**Comment by KengoTODA** [comment]
Yes, and bump up major versions when we break any backward compatibilities.

**Comment by ThrawnCA** [comment]
What is the API, then?

**Comment by KengoTODA** [comment]
The interface of task and extension, in my understanding.

**Comment by ThrawnCA** [comment]
And is that interface documented somewhere? I'm not sure off-hand.

**Comment by KengoTODA** [comment]
the new implementation has introduced semantic-release with documented interface, so I will close this issue.

**Pull request closed without merging**
