### PR TITLE
feat: print report to console when reporting is not specified (#172)

### PR DESCRIPTION
**Pull request by blzsaa**
Possible solution for #172 print to console

### CODE REVIEW

**Review by jscancella — APPROVED** [review]
LGTM

**Comment by jscancella** [comment]
@KengoTODA thoughts on this?

**Comment by KengoTODA** [comment]
@jscancella sorry for my late response.

this PR breaks backward compatibility, so I wanna release this as a part of v5 release. 
Could you review and merge #555 first? Then we can release v5.0.0-beta1 with this feature.

**Comment by KengoTODA** [comment]
I've merged these changes to the `beta` branch manually. Thanks for your contribution!

**Pull request closed without merging**
