### PR TITLE
Remove problematic method reference causing problems with Gradle 4.10

### PR DESCRIPTION
**Pull request by chali**

### CODE REVIEW

**Comment by KengoTODA** [comment]
Thanks @chali, I'll merge this.

**Comment by chali** [comment]
Awesome! Do you plan to release this fix soon?

**Comment by davidburstromspotify** [comment]
@KengoTODA Please, can you see a release of this fix soon? We're quite a few people who are eager to use Gradle 4.10. お願いします。

**Comment by perlun** [comment]
@KengoTODA Sorry to be one of the "me-too":ers here, but it would be great to get this released (since Gradle 4.10 is needed to support the soon-coming Java 11 release).

(I'll try building a version from source for now.)

**Pull request merged**
